### ISSUE TITLE
1 January in sms notification date

### ISSUE THREAD

**Issue by tchantchan** [Vin4ter/Ubports-Onclite-redmi7#15]
This is not a terrible bug but the notification date is always 1 January.

I can't use Pure maps, the GPS signal is ok but I can't make any search.
Cycle message app doesn't work. Teleport works fine.

I don't know if i have to report bugs to the app github, i'm knew in this business.

Everythings else works fine, thanks a lot for this port. 
I saw recently (cause i'm not famaliar with github) an old readme with more details step to install ( unlock boatloader, fastboot, twrp... ), it can help more people to have a try whith UT.

Thanks for your work!

**Comment by Vin4ter** [comment]
I do not know if this is just you ,but I have the date and time set
automatically over the network if you select the correct time zone.

сб, 28 нояб. 2020 г., 11:36 tchantchan <notifications@github.com>:

**Comment by Vin4ter** [comment]
The problem with pure maps is not a problem with my ubports port, but a
problem with the program itself. If you want to use gps maps you can use
uNav it works very well

сб, 28 нояб. 2020 г., 12:52 Alex Tikhanov <supirlelik96@gmail.com>:

**Comment by tchantchan** [comment]
For the date problem, it stricly in sms notifacations the others date and time works fine so it's not really a problem... I will try Unav to check.
Other question, is the OTA avaible or not? My first install was  3 weeks ago and I re-install it 3 days ago, it doesn't look the same, for exemple Unav wasn't already load this time.
Thanks again.
