### ISSUE TITLE
Stuck in bootloop

### ISSUE THREAD

**Issue by JasonHaddad-88** [Vin4ter/Ubports-Onclite-redmi7#16]
Hello, I applied the steps exactly as you stated (via TWRP and fastboot), yet I am stuck in bootloop.
I have read that LineageOS 16 is required for Redmi Note 7 yet in your Redmi 7 tutorial it was not needed. Where have I messed up?

**Comment by tchantchan** [comment]
Hi,
It worked for me 2 weeks ago.
Did you use GenomBuntu or Ub Cartel?
I had an issue the first time in twrp cause i didn't select Vendor when I flash Mashkoukras Vendor but it's obius...
Retry all the step it should work. 
I'm not an expert i just saw your issue has no answer since two days

**Comment by JasonHaddad-88** [comment]
I remember I did flash UBCartel. If not, should I reflash as-is or clear some stuff before?

**Comment by tchantchan** [comment]
Really not an expert but wipe the data ect... again. 
Flash it. 
UT run well on this device. Thanks Vin4ter

**Comment by JasonHaddad-88** [comment]
How much time did it take for first boot? And did you flash mashkoukras via PC or am I able to flash it via TWRP?

**Comment by JasonHaddad-88** [comment]
Everything worked now, thank you
Flashed via TWRP

**Comment by tchantchan** [comment]
Nice!
You can close this issues.
