### ISSUE TITLE
Phone not charging

### ISSUE THREAD

**Issue by JasonHaddad-88** [Vin4ter/Ubports-Onclite-redmi7#17]
Phone is not charging at all, even when off.
Cleared "cache, dalvik cache, and data"
Flashed vendor via TWRP as "vendor"
Flashed everything else in order
USB port working fine, tried by plugging in a flash drive; charger is fine, too, as I plugged two working ones to no avail.
Anyone else facing such an issue?
Phone boots to "fastboot" whenever I plug in charger.

EDIT: Battery indicator is faulty and LED light does not work

**Comment by Vin4ter** [comment]
The smartphone is charging, just does not show uboorts that charging is
going on

ср, 9 дек. 2020 г., 0:53 JasonHaddad-88 <notifications@github.com>:
