### ISSUE TITLE
flash and kernel boot success but can't enter ubuntu.

### ISSUE THREAD

**Issue by MagicalGirlXi** [Vin4ter/Ubports-Onclite-redmi7#19]
with the required img and zip flashed, boot will stuck in "Redmi by Xiaomi" logo , and I connect to device by telnet, and I see the process running. 
Ps result is below
`PID   USER     COMMAND
    1 0        {init} /bin/sh /init
    2 0        [kthreadd]
    3 0        [ksoftirqd/0]
    5 0        [kworker/0:0H]
    6 0        [kworker/u16:0]
    7 0        [rcu_preempt]
    8 0        [rcu_sched]
    9 0        [rcu_bh]
   10 0        [rcuop/0]
   11 0        [rcuos/0]
   12 0        [rcuob/0]
   13 0        [migration/0]
   14 0        [lru-add-drain]
   15 0        [cpuhp/0]
   16 0        [cpuhp/1]
   17 0        [migration/1]
   18 0        [ksoftirqd/1]
   20 0        [kworker/1:0H]
   21 0        [rcuop/1]
   22 0        [rcuos/1]
   23 0        [rcuob/1]
   24 0        [cpuhp/2]
   25 0        [migration/2]
   26 0        [ksoftirqd/2]
   27 0        [kworker/2:0]
   28 0        [kworker/2:0H]
   29 0        [rcuop/2]
   30 0        [rcuos/2]
   31 0        [rcuob/2]
   32 0        [cpuhp/3]
   33 0        [migration/3]
   34 0        [ksoftirqd/3]
   35 0        [kworker/3:0]
   36 0        [kworker/3:0H]
   37 0        [rcuop/3]
   38 0        [rcuos/3]
   39 0        [rcuob/3]
   40 0        [cpuhp/4]
   41 0        [migration/4]
   42 0        [ksoftirqd/4]
   43 0        [kworker/4:0]
   44 0        [kworker/4:0H]
   45 0        [rcuop/4]
   46 0        [rcuos/4]
   47 0        [rcuob/4]
   48 0        [cpuhp/5]
   49 0        [migration/5]
   50 0        [ksoftirqd/5]
   51 0        [kworker/5:0]
   52 0        [kworker/5:0H]
   53 0        [rcuop/5]
   54 0        [rcuos/5]
   55 0        [rcuob/5]
   56 0        [cpuhp/6]
   57 0        [migration/6]
   58 0        [ksoftirqd/6]
   59 0        [kworker/6:0]
   60 0        [kworker/6:0H]
   61 0        [rcuop/6]
   62 0        [rcuos/6]
   63 0        [rcuob/6]
   64 0        [cpuhp/7]
   65 0        [migration/7]
   66 0        [ksoftirqd/7]
   67 0        [kworker/7:0]
   68 0        [kworker/7:0H]
   69 0        [rcuop/7]
   70 0        [rcuos/7]
   71 0        [rcuob/7]
   72 0        [kdevtmpfs]
   73 0        [netns]
   76 0        [smd_channel_clo]
   77 0        [kworker/u17:0]
   78 0        [kworker/u16:1]
   79 0        [smsm_cb_wq]
   80 0        [msm_watchdog]
   81 0        [oom_reaper]
   82 0        [writeback]
   83 0        [kcompactd0]
   84 0        [crypto]
   85 0        [bioset]
   86 0        [kblockd]
   87 0        [irq/62-tsens-up]
   88 0        [irq/63-tsens-cr]
   89 0        [edac-poller]
   90 0        [system]
   91 0        [devfreq_wq]
   92 0        [governor_msm_ad]
   93 0        [cfg80211]
   94 0        [irq/108-cpr3]
   95 0        [kworker/0:2]
   96 0        [irq/149-qpnp_lc]
   97 0        [kworker/0:3]
   98 0        [kworker/4:1]
   99 0        [ipa_power_mgmt]
  100 0        [sps_ipa_power_m]
  101 0        [ipawq36]
  102 0        [iparepwq36]
  103 0        [kworker/u17:1]
  104 0        [ipawq33]
  105 0        [iparepwq33]
  106 0        [ipawq34]
  107 0        [iparepwq34]
  108 0        [ipa_rm_wq]
  109 0        [ipa_interrupt_w]
  110 0        [ipa_holb_wq]
  111 0        [kworker/5:1]
  136 0        [kswapd0]
  137 0        [vmstat]
  138 0        [SquashFS read w]
  139 0        [ecryptfs-kthrea]
  173 0        [rot_workq_0]
  174 0        [mdss_dsi_event]
  175 0        [mdss_dsi_dba]
  176 0        [mem_share_svc]
  177 0        [qmi_hndl0000000]
  178 0        [msm_ipc_router]
  179 0        [hwrng]
  181 0        [diag_real_time_]
  182 0        [diag_wq]
  183 0        [DIAG_USB_diag]
  184 0        [diag_cntl_wq]
  185 0        [diag_dci_wq]
  186 0        [DIAG_SMD_MODEM_]
  187 0        [DIAG_SMD_MODEM_]
  188 0        [DIAG_SMD_MODEM_]
  189 0        [DIAG_SMD_MODEM_]
  190 0        [DIAG_SMD_MODEM_]
  191 0        [DIAG_SMD_LPASS_]
  192 0        [DIAG_SMD_LPASS_]
  193 0        [DIAG_SMD_LPASS_]
  194 0        [DIAG_SMD_LPASS_]
  195 0        [DIAG_SMD_LPASS_]
  196 0        [DIAG_SMD_WCNSS_]
  197 0        [DIAG_SMD_WCNSS_]
  198 0        [DIAG_SMD_WCNSS_]
  199 0        [DIAG_SMD_WCNSS_]
  200 0        [DIAG_SMD_WCNSS_]
  201 0        [DIAG_SMD_SENSOR]
  202 0        [DIAG_SMD_SENSOR]
  203 0        [DIAG_SMD_SENSOR]
  204 0        [DIAG_SMD_SENSOR]
  205 0        [DIAG_SMD_SENSOR]
  206 0        [DIAG_SMD_CDSP_C]
  207 0        [DIAG_SMD_CDSP_D]
  208 0        [DIAG_SMD_CDSP_C]
  209 0        [DIAG_SMD_CDSP_D]
  210 0        [DIAG_SMD_CDSP_D]
  211 0        [DIAG_SOCKMODEM_]
  212 0        [DIAG_SOCKMODEM_]
  213 0        [DIAG_SOCKMODEM_]
  214 0        [DIAG_SOCKMODEM_]
  215 0        [DIAG_SOCKMODEM_]
  216 0        [DIAG_SOCKLPASS_]
  217 0        [DIAG_SOCKLPASS_]
  218 0        [DIAG_SOCKLPASS_]
  219 0        [DIAG_SOCKLPASS_]
  220 0        [DIAG_SOCKLPASS_]
  221 0        [DIAG_SOCKWCNSS_]
  222 0        [DIAG_SOCKWCNSS_]
  223 0        [DIAG_SOCKWCNSS_]
  224 0        [DIAG_SOCKWCNSS_]
  225 0        [DIAG_SOCKWCNSS_]
  226 0        [DIAG_SOCKSENSOR]
  227 0        [DIAG_SOCKSENSOR]
  228 0        [DIAG_SOCKSENSOR]
  229 0        [DIAG_SOCKSENSOR]
  230 0        [DIAG_SOCKSENSOR]
  231 0        [DIAG_SOCKDIAG_C]
  232 0        [DIAG_SOCKDIAG_D]
  233 0        [DIAG_SOCKDIAG_C]
  234 0        [DIAG_SOCKDIAG_D]
  235 0        [DIAG_SOCKDIAG_D]
  236 0        [DIAG_SOCKCDSP_C]
  237 0        [DIAG_SOCKCDSP_D]
  238 0        [DIAG_SOCKCDSP_C]
  239 0        [DIAG_SOCKCDSP_D]
  240 0        [DIAG_SOCKCDSP_D]
  241 0        [DIAG_CNTL_SOCKE]
  247 0        [kgsl-workqueue]
  248 0        [kgsl-mementry]
  249 0        [kgsl_worker_thr]
  250 0        [irq/19-arm-smmu]
  251 0        [kgsl-events]
  252 0        [kgsl_devfreq_wq]
  253 0        [bioset]
  254 0        [bioset]
  255 0        [bioset]
  256 0        [bioset]
  257 0        [bioset]
  258 0        [bioset]
  259 0        [bioset]
  260 0        [bioset]
  261 0        [bioset]
  262 0        [bioset]
  263 0        [bioset]
  264 0        [bioset]
  265 0        [bioset]
  266 0        [bioset]
  267 0        [bioset]
  268 0        [bioset]
  269 0        [bioset]
  270 0        [bioset]
  271 0        [bioset]
  272 0        [bioset]
  273 0        [bioset]
  274 0        [bioset]
  275 0        [bioset]
  276 0        [bioset]
  277 0        [bioset]
  278 0        [qseecom-unreg-l]
  279 0        [irq/283-ant-swi]
  280 0        [qcrypto_seq_res]
  301 0        [spi6]
  302 0        [sharedmem_qmi_w]
  303 0        [qmi_hndl0000000]
  308 0        [uether]
  309 0        [gt1x_wq]
  310 0        [gt1x_workthread]
  312 0        [msm_vidc_worker]
  313 0        [pm_workerq_venu]
  314 0        [irq/44-arm-smmu]
  315 0        [irq/27-arm-smmu]
  316 0        [irq/28-arm-smmu]
  317 0        [irq/26-arm-smmu]
  318 0        [msm_cci_wq]
  319 0        [msm_cci_wq]
  320 0        [kworker/2:1]
  321 0        [kworker/3:1]
  322 0        [msm_cpp_workque]
  323 0        [irq/286-chgr-er]
  324 0        [irq/287-chg-sta]
  325 0        [irq/294-otg-fai]
  326 0        [irq/298-high-du]
  327 0        [irq/299-input-c]
  328 0        [irq/301-switche]
  329 0        [irq/302-bat-tem]
  330 0        [irq/304-bat-ov]
  331 0        [irq/305-bat-low]
  332 0        [irq/306-bat-the]
  333 0        [irq/307-bat-ter]
  334 0        [irq/310-usbin-c]
  335 0        [irq/311-usbin-v]
  336 0        [irq/312-usbin-u]
  337 0        [irq/313-usbin-o]
  338 0        [irq/314-usbin-p]
  339 0        [irq/316-usbin-s]
  340 0        [irq/317-usbin-i]
  341 0        [irq/318-typec-o]
  342 0        [irq/320-typec-c]
  343 0        [irq/321-typec-v]
  344 0        [irq/323-typec-a]
  345 0        [irq/324-typec-l]
  346 0        [irq/327-wdog-ba]
  347 0        [irq/329-aicl-do]
  348 0        [irq/334-flash-s]
  349 0        [irq/336-ilim2-s]
  350 0        [qmi_tmd_wq]
  351 0        [qmi_svc_event_w]
  352 0        [irq/141-bcl-vba]
  353 0        [irq/143-bcl-vba]
  354 0        [irq/144-bcl-vba]
  355 0        [kworker/6:1]
  356 0        [dm_bufio_cache]
  357 0        [mmc_clk_gate/mm]
  358 0        [irq/16-7824900.]
  359 0        [irq/15-mmc0]
  360 0        [kworker/1:2]
  361 0        [bioset]
  362 0        [sdhci_msm_pm_qo]
  363 0        [mmc-cmdqd/0]
  364 0        [bioset]
  365 0        [mmcqd/0rpmb]
  366 0        [mmc_clk_gate/mm]
  367 0        [irq/77-7864900.]
  368 0        [irq/76-mmc1]
  369 0        [irq/78-7864900.]
  370 0        [apr_driver]
  371 0        [ipv6_addrconf]
  372 0        [irq/372-adsp]
  373 0        [sysmon_wq]
  374 0        [irq/404-wcnss]
  375 0        [irq/340-modem]
  376 0        [irq/82-hs_phy_i]
  377 0        [irq/84-pwr_even]
  378 0        [irq/83-ss_phy_i]
  379 0        [usb_bam_wq]
  380 0        [irq/437-qg-vbat]
  381 0        [irq/438-qg-vbat]
  382 0        [irq/439-qg-fifo]
  383 0        [irq/440-qg-good]
  384 0        [core_ctl/0]
  385 0        [core_ctl/4]
  399 0        [rq_stats]
  400 0        [msm_perf:events]
  401 0        [irq/39-arm-smmu]
  402 0        [irq/154-qpnp_fl]
  403 0        [irq/153-qpnp_fl]
  404 0        [irq/151-qpnp_fl]
  405 0        [ipa_A7_svc]
  406 0        [qmi_hndl0000000]
  407 0        [clnt_req]
  408 0        [clnt_resp]
  409 0        [clnt_req]
  443 0        [kworker/0:1H]
  444 0        [kworker/5:1H]
  445 0        [kworker/6:1H]
  455 0        [kworker/7:1H]
  460 0        [kworker/4:1H]
  461 0        [kworker/7:1]
  557 0        {telnet} /bin/sh /scripts/panic/telnet
  581 0        /bin/busybox udhcpd
  583 0        /bin/busybox telnetd -b 192.168.2.15:23 -l /bin/sh
  593 0        [kworker/3:1H]
  595 0        [kworker/1:5]
  599 0        [kworker/u16:3]
  601 0        [kworker/1:3]
  606 0        [kworker/1:0]
  607 0        /bin/sh
  608 0        {exe} ps`
I use twrp 3.3.2b and based on MIUI 11.0.7(Android 9).
I wonder if I based on the wrong system? Which version of MIUI do you use to tranfer to ubport?

**Comment by MagicalGirlXi** [comment]
finally i fix the issue 
I used a custom twrp, when i change to a official twrp, all the things run well!!!!

**Comment by Vin4ter** [comment]
Good :)

чт, 31 дек. 2020 г., 20:17 magicgirlxi <notifications@github.com>:
