### ISSUE TITLE
Install Error 6: in TWRP install

### ISSUE THREAD

**Issue by b23prodtm** [Vin4ter/Ubports-Onclite-redmi7#2]
The file UBports_Vendor.zip failed for unknown reason, but the system would boot anyway after installing the other zip files.

**Comment by Vin4ter** [comment]
Hello, I will soon collect all the installation files in one zip archive
with the new ubports rootfs for twrp ,and update it on my gitHub

сб, 3 окт. 2020 г., 15:07 Tiana Rakoto Arimanana <notifications@github.com>:

**Comment by b23prodtm** [comment]
HI 
Thank you Nice work, the fix for camera’s become obsolete, it works out of the box ^^
B23PRO

**Comment by Vin4ter** [comment]
The camera does not work correctly from the box and you need to install the
camera by entering

wget
https://static.peat-network.xyz/junk/ubports/com.ubuntu.camera_3.1.2+gstdroid3_armhf.click
pkcon install-local --allow-untrusted
com.ubuntu.camera_3.1.2+gstdroid3_armhf.click

сб, 3 окт. 2020 г., 15:23 Tiana Rakoto Arimanana <notifications@github.com>:

> HI
> Thank you Nice work, the fix for camera’s become obsolete, it works out of
> the box ^^
> B23PRO
>

**Comment by bibarub** [comment]
old
