### ISSUE TITLE
installer support

### ISSUE THREAD

**Issue by kaiyes** [Vin4ter/Ubports-Onclite-redmi7#8]
Hi, 

How hard will it be to add installer support ? I might buy this device & try

**Comment by isimne** [comment]
@kaiyes It's not difficult. But it's better to try other devices first

**Comment by kaiyes** [comment]
@isimne thanks for answering. I got the impression onclite could be that device since it sits right on top in terms of maturity. 

If not, which devices you recommend ? Like I saw one plus 6t has unofficial support so guess that could be next ? 


![Screenshot 2020-11-02 at 6 02 37 AM](https://user-images.githubusercontent.com/5293742/97819153-03a7c000-1cd1-11eb-83fc-0f6cc3b0e046.png)

**Comment by Vin4ter** [comment]
NO installer support ,but only twrp recovery
